export const TEMPLATE_VARIABLES = {

};

export const TEMPLATE_IDENTIFIER = {
	OPENING_IDENTIFIER: '{{',
	CLOSING_IDENTIFIER: '}}'
};


export const PACKAGE_JSON_TEMPLATES = {
	SCRIPTS: `${TEMPLATE_IDENTIFIER.OPENING_IDENTIFIER}SCRIPTS${TEMPLATE_IDENTIFIER.CLOSING_IDENTIFIER}`,
	PROJECT_NAME: `${TEMPLATE_IDENTIFIER.OPENING_IDENTIFIER}PROJECT_NAME${TEMPLATE_IDENTIFIER.CLOSING_IDENTIFIER}`,
	DEV_DEPENDENCIES: `${TEMPLATE_IDENTIFIER.OPENING_IDENTIFIER}DEV_DEPENDENCIES${TEMPLATE_IDENTIFIER.CLOSING_IDENTIFIER}`,
	DEPENDENCIES: `${TEMPLATE_IDENTIFIER.OPENING_IDENTIFIER}DEPENDENCIES${TEMPLATE_IDENTIFIER.CLOSING_IDENTIFIER}`,
};
